### ISSUE TITLE
Support for `True`, `False`, `None` keywords

### ISSUE THREAD

**Issue by mtvch** [balance-platform/ex_pression#2]
Currently `json` keywords `true`, `false`, `null` are supported.
I propose to add support for python's  `True`, `False`, `None`. This might help people who are used to python's syntax and reduce number of syntax errors.
I don't see any downsides.
@sofakingworld  What do you think?

**Comment by sofakingworld** [comment]
@mtvch 
> I don't see any downsides.
Agree.
Good task!
